name: camlica_pts
description: "a new flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.2+6

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  shared_preferences: ^2.4.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  mobile_scanner: ^6.0.3
  get: ^4.6.6
  intl: ^0.19.0
  flutter_hooks: ^0.20.5
  package_info_plus: ^8.2.1
  url_launcher: ^6.3.1
  flutter_riverpod: ^2.6.1
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  form_builder_file_picker: ^4.3.0
  riverpod: ^2.6.1
  form_builder_image_picker: ^4.2.0
  socket_io_client: ^3.0.2
  firebase_core: ^3.11.0
  firebase_messaging: ^15.2.2
  badges: ^3.1.2
  form_builder: ^1.0.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.3
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/map.jpeg
